---
- name:


- name: Download and Unarchive Ansible Tower Bundle Installer
  unarchive:
    src: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz
    dest: /root/
    remote_src: yes
  tags: tower
