---
- name: Check to see if the system is subscribed
  command: subscription-manager status
  register: result
  ignore_errors: True

- name: Register to RHN and attach  SKU through Activation Key
  redhat_subscription:
    state: present
    activationkey: "{{ tower_activation_key }}"
    org_id: "{{ rhn_org_id }}"
  tags: register

- name: Disable All Repositories
  command: subscription-manager repos --disable "*"
  tags: register

- name: Enable Satellite repositories
  command: /usr/sbin/subscription-manager repos --enable="{{item}}"
  with_items: "{{ tower_repos }}"
  tags: register
